server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      #注意此处配置，seata在cloud.alibaba下一级
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    #注意此处配置，nacos在cloud下一级
    nacos:
      discovery:
        server-addr: localhost:8848
    #注意此处配置，sentinel在cloud下一级（错误配置会导致sentinel不能正确监控）
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: seata-order-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: 123456

#sentinel图形化监控控界面
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持

logging:
  level:
    io:
      seata: info

  #mybatis 配置
mybatis:
  #config-locations:
  #classpath: mybatis/mybatis-config.xml
  mapperLocations: com/atguigu/springcloud/alibaba/dao/xml/*.xml
  mapper-locations[0]:
    classpath: com/atguigu/springcloud/alibaba/dao/xml/*.xml
  type-aliases-package: com.atguigu.springcloud.alibaba.dao.mapper
  configuration:
    map-underscore-to-camel-case: true
