package com.atguigu.springcloud.alibaba.dao.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_storage
 */
public class Storage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   产品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     * Database Column Remarks:
     *   总库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     * Database Column Remarks:
     *   已用库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.used
     *
     * @mbg.generated
     */
    private Integer used;

    /**
     * Database Column Remarks:
     *   剩余库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.residue
     *
     * @mbg.generated
     */
    private Integer residue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.id
     *
     * @return the value of t_storage.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.id
     *
     * @param id the value for t_storage.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.product_id
     *
     * @return the value of t_storage.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.product_id
     *
     * @param productId the value for t_storage.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.total
     *
     * @return the value of t_storage.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.total
     *
     * @param total the value for t_storage.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.used
     *
     * @return the value of t_storage.used
     *
     * @mbg.generated
     */
    public Integer getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.used
     *
     * @param used the value for t_storage.used
     *
     * @mbg.generated
     */
    public void setUsed(Integer used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.residue
     *
     * @return the value of t_storage.residue
     *
     * @mbg.generated
     */
    public Integer getResidue() {
        return residue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.residue
     *
     * @param residue the value for t_storage.residue
     *
     * @mbg.generated
     */
    public void setResidue(Integer residue) {
        this.residue = residue;
    }
}