package com.atguigu.springcloud.alibaba.dao.mapper;

import com.atguigu.springcloud.alibaba.dao.entity.Storage;
import org.apache.ibatis.annotations.Param;

public interface StorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int insert(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int insertSelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    Storage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Storage record);

    //扣减库存
    int decrease(@Param("productId") Long productId, @Param("count") Integer count);
}