package com.atguigu.springcloud.alibaba.dao.mapper;

import com.atguigu.springcloud.alibaba.dao.entity.Order;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);


    /**
     * [1 新建订单]
     * @author: liuzx
     * @date: 2020/12/9
     **/
    int createOrder(com.atguigu.springcloud.alibaba.domain.Order order);


    /**
     * [修改订单状态，从0改成1]
     * @author: liuzx
     * @date: 2020/12/9
     **/
    int updateOrder(@Param("userId") Long userId, @Param("status") Integer status);
}