package com.atguigu.springcloud.alibaba.dao.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_account
 */
public class Account implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   总额度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.total
     *
     * @mbg.generated
     */
    private Long total;

    /**
     * Database Column Remarks:
     *   已用余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.used
     *
     * @mbg.generated
     */
    private Long used;

    /**
     * Database Column Remarks:
     *   剩余可用额度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.residue
     *
     * @mbg.generated
     */
    private Long residue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.id
     *
     * @return the value of t_account.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.id
     *
     * @param id the value for t_account.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.user_id
     *
     * @return the value of t_account.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.user_id
     *
     * @param userId the value for t_account.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.total
     *
     * @return the value of t_account.total
     *
     * @mbg.generated
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.total
     *
     * @param total the value for t_account.total
     *
     * @mbg.generated
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.used
     *
     * @return the value of t_account.used
     *
     * @mbg.generated
     */
    public Long getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.used
     *
     * @param used the value for t_account.used
     *
     * @mbg.generated
     */
    public void setUsed(Long used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.residue
     *
     * @return the value of t_account.residue
     *
     * @mbg.generated
     */
    public Long getResidue() {
        return residue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.residue
     *
     * @param residue the value for t_account.residue
     *
     * @mbg.generated
     */
    public void setResidue(Long residue) {
        this.residue = residue;
    }
}